# permissions for end users to view streamingresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: streamingress-viewer-role
rules:
- apiGroups:
  - nginx-stream.jeffthecoder.xyz
  resources:
  - streamingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nginx-stream.jeffthecoder.xyz
  resources:
  - streamingresses/status
  verbs:
  - get
