# permissions for end users to edit streamingresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: streamingress-editor-role
rules:
- apiGroups:
  - nginx-stream.jeffthecoder.xyz
  resources:
  - streamingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nginx-stream.jeffthecoder.xyz
  resources:
  - streamingresses/status
  verbs:
  - get
